---
title: blogpost4
author: The_A+_team
date: '2022-11-03'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-11-03T23:33:20-04:00'
featuredVideo: ~
featuredImage: ~
---


<div id="TOC">

</div>

<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages
## ───────────────────────────────────────
## tidyverse 1.3.2 ──</code></pre>
<pre><code>## ✔ ggplot2 3.3.6     ✔ purrr   0.3.4
## ✔ tibble  3.1.6     ✔ stringr 1.4.0
## ✔ tidyr   1.2.0     ✔ forcats 0.5.2
## ✔ readr   2.1.2     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>air1 &lt;- read_csv(&quot;AIRTRANS_CO2.csv&quot;, show_col_types = FALSE) %&gt;% 
  filter(LOCATION == &quot;USA&quot;, values_drop_na = TRUE) %&gt;% 
  arrange(order(Time)) %&gt;% 
  select(-POLLUTANT, -MEASURE, -FLIGHT, -FREQUENCY, -SOURCE, -SEASONALITY, -TIME, -`Flag Codes`, -Flags, -Pollutant, -LOCATION) %&gt;% 
  filter(Time &gt; 2014 &amp; Time &lt; 2020) %&gt;% 
  rename(flight_type = `Flight type`, source_of_emissions = `Source of emissions`, Year = Time, Emission = Value) %&gt;%
  ungroup() 

air1</code></pre>
<pre><code>## # A tibble: 180 × 8
##    Country  Measure  flight_type  Frequency source_of_emissio… Seasonality Year 
##    &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;        &lt;chr&gt;     &lt;chr&gt;              &lt;chr&gt;       &lt;chr&gt;
##  1 United … tonnes … All flights  Annual    &quot;\&quot;(A) - Domestic… Non season… 2015 
##  2 United … tonnes … All flights  Annual    &quot;\&quot;(E) - Internat… Non season… 2015 
##  3 United … tonnes … All flights  Annual    &quot;Bridging item - … Non season… 2015 
##  4 United … tonnes … Passenger f… Annual    &quot;\&quot;(A) - Domestic… Non season… 2015 
##  5 United … tonnes … Passenger f… Annual    &quot;\&quot;(E) - Internat… Non season… 2015 
##  6 United … tonnes … Passenger f… Annual    &quot;Bridging item - … Non season… 2015 
##  7 United … tonnes … Freight fli… Annual    &quot;\&quot;(A) - Domestic… Non season… 2015 
##  8 United … tonnes … Freight fli… Annual    &quot;\&quot;(E) - Internat… Non season… 2015 
##  9 United … tonnes … Freight fli… Annual    &quot;Bridging item - … Non season… 2015 
## 10 United … tonnes … All flights  Annual    &quot;\&quot;(A) - Domestic… Non season… 2016 
## # … with 170 more rows, and 1 more variable: Emission &lt;dbl&gt;</code></pre>
<pre class="r"><code>air1 %&gt;% ggplot(aes(x = Year, y = Emission)) +
  geom_point(aes(color = flight_type), size = 1) +
  stat_smooth(aes(group = flight_type, color = flight_type), alpha = 0.5, geom = &quot;line&quot;) + labs(title = &quot;CO2 emission by year&quot;, x = &quot;year&quot;, y = &quot;CO2 Emission (tonnes)&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/airline%20EDA-1.png" width="672" /></p>
<pre class="r"><code>air1 %&gt;% ggplot(aes(factor(flight_type), Emission)) +
  geom_boxplot() + labs(title = &quot;CO2 emissions by flight type&quot;, y = &quot;CO2 Emission (tonnes)&quot;) + coord_flip()</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/airline%20EDA-2.png" width="672" /></p>
<pre class="r"><code>air1 %&gt;% ggplot(aes(factor(source_of_emissions), Emission)) + geom_boxplot() + theme(axis.text.x = element_text(size=5, angle=45, vjust=0.8, hjust=0.8)) + labs(title = &quot;CO2 emisssions by sources&quot;, x = &quot;year&quot;, y = &quot;CO2 Emission (tonnes)&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/airline%20EDA-3.png" width="672" /></p>
<p>In blogpost 4, in order to explore further the relationship between variables, we changed the bar graph in blogpost 2 into scatterplot with more aesthetic. We make graph of emissions of all flights, freight flights, and passenger flights, and we put the data of these three types of flight at the same year into the same axis. In this way, we can easily examine the trend of emissions of different types increasing with years and at the same time compare every year emissions of different types of flights. We smooth the data to remove noise from the dataset, which allows important patterns to clearly stand out. And we can see an upward trend of emissions of the types of flights.</p>
<p>In the second graph, we are trying to explore the summarized trend of emissions of three types flight in five years, so we combine data in five years and makes a boxplot. Boxplot is used to show overall patterns of response for a group. From the boxplot, we have the range of emissions created by the three types. As passenger flights have more emissions than freight flights, we can conclude most emissions come from passenger flights.</p>
<p>In the third graph, we try to extend to include the relationship between resources of emissions and emissions for a more comprehensive explanation of emission trend. In the more detailed graph, there are 12 sources of emissions, and “(G)-international flight departing from country A, operated by an airline that is non-resident in country A” is the resource that created biggest influence, while B and F are the resources that created smallest influence.</p>
<pre class="r"><code>library(dplyr)
library(tidyverse)
Agri &lt;- read_csv(&quot;FAOSTAT.csv&quot;, show_col_types = FALSE) 
Agri2 &lt;- 
  Agri %&gt;% filter(Area == &quot;United States of America&quot;) %&gt;%
  filter(str_detect(Element, &quot;CO2eq&quot;)) %&gt;%
  mutate(unit = &quot;tonnes&quot;) %&gt;%
  select(Area, Item, Element,unit, Y2015:Y2019) %&gt;%
  pivot_longer(c(Y2015:Y2019),
               names_to = &quot;year_new&quot;, values_to = &quot;emission&quot;) %&gt;%
  mutate(total = emission * 1000) %&gt;%
  select(-emission) %&gt;%
  arrange(order(year_new)) %&gt;%
  group_by(year_new, Item, Area, unit) %&gt;%
  summarize(sum_emission = sum(total, na.rm = TRUE, count = n()), Element) %&gt;%
  rename(Country = Area, Measure = unit, Emission = sum_emission, Year = year_new, source_of_emissions = Item)</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;year_new&#39;, &#39;Item&#39;, &#39;Area&#39;, &#39;unit&#39;. You can
## override using the `.groups` argument.</code></pre>
<pre class="r"><code>Agri2</code></pre>
<pre><code>## # A tibble: 445 × 6
## # Groups:   Year, source_of_emissions, Country, Measure [120]
##    Year  source_of_emissions     Country       Measure  Emission Element        
##    &lt;chr&gt; &lt;chr&gt;                   &lt;chr&gt;         &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;          
##  1 Y2015 AFOLU                   United State… tonnes     4.47e8 Emissions (CO2…
##  2 Y2015 AFOLU                   United State… tonnes     4.47e8 Emissions (CO2…
##  3 Y2015 AFOLU                   United State… tonnes     4.47e8 Emissions (CO2…
##  4 Y2015 Agricultural Soils      United State… tonnes     9.09e8 Emissions (CO2…
##  5 Y2015 Agricultural Soils      United State… tonnes     9.09e8 Emissions (CO2…
##  6 Y2015 Agricultural Soils      United State… tonnes     9.09e8 Emissions (CO2…
##  7 Y2015 Agricultural Soils      United State… tonnes     9.09e8 Emissions (CO2…
##  8 Y2015 Burning - Crop residues United State… tonnes     9.06e6 Emissions (CO2…
##  9 Y2015 Burning - Crop residues United State… tonnes     9.06e6 Emissions (CO2…
## 10 Y2015 Burning - Crop residues United State… tonnes     9.06e6 Emissions (CO2…
## # … with 435 more rows</code></pre>
<pre class="r"><code>Agri2 %&gt;%
  filter(source_of_emissions == &quot;Emissions on agricultural land&quot; | source_of_emissions == &quot;Farm-gate emissions&quot; | source_of_emissions == &quot;IPCC Agriculture&quot; | 
           source_of_emissions == &quot;AFOLU&quot; | source_of_emissions == &quot;Enteric Fermentation&quot;) %&gt;%
  ggplot(aes(x = source_of_emissions, y = Emission)) +
  geom_point(position = &quot;jitter&quot;) + labs(title = &quot;CO2 emission by sources&quot;, x = &quot;source of emissions&quot;, y = &quot;CO2 Emission (tonnes)&quot;) + theme(axis.text.x = element_text(size=9, angle=45, vjust=0.8, hjust=0.8))</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/agriculture%20EDA-1.png" width="672" /></p>
<pre class="r"><code>Agri2 %&gt;%
  filter(source_of_emissions == &quot;Emissions on agricultural land&quot; | source_of_emissions == &quot;Farm-gate emissions&quot; | source_of_emissions == &quot;IPCC Agriculture&quot; | 
           source_of_emissions == &quot;AFOLU&quot; | source_of_emissions == &quot;Enteric Fermentation&quot;) %&gt;%
  ggplot(aes(factor(source_of_emissions),
                    Emission)) +
  geom_boxplot() + coord_flip() + labs(title = &quot;CO2 emission by sources&quot;, x = &quot;Emissions(tonnes)&quot;, y = &quot;source of emission&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/agriculture%20EDA-2.png" width="672" /></p>
<p>In the last blogpost, we plotted the CO2 emission for the largest sources as a pie chart to show the proportion of each factor. The emission in different year is separately plotted. For blogpost 4, we are trying to focus on the source of emission itself. Therefore, we made source or emission vs. amount of emission, and each point is representing the amount of CO2 that the source released in a specific years. In this way, the graph is easier and clear for the audience to interpret.</p>
<p>Furthermore, we did a box-plot for the data. As a result, we now can see a different distribution of data point for each source. This is beneficial because it provides more detail for us to examine those with unusual data point. For example, we saw that the AFOLU and Agriculture land has some extreme outliers in some of the years. We could then trace back to the original data and possibly find a cause to that.</p>
<p>Additionally, we could cross datasets to see if that is a common trend for other sectors. If these trends are commonly shared, it is possible that there is some variable that can be used in modeling and thus predict the CO2 emission for future. For instance, we could construct a model that shows if we know that one sector has a higher emission this year, some of the other source might also have an increased emission by some percentage</p>
<pre class="r"><code>library(tidyverse)
electricity &lt;- read_csv(&quot;electricity_co2.csv&quot;, show_col_types = FALSE)
electricity1 &lt;- electricity %&gt;%
  filter(State == &quot;State Total&quot;) %&gt;%
  filter(Time &gt; 2014 &amp; Time &lt; 2020) %&gt;%
  select(-Pollutant, -Measure) %&gt;% 
  rename(electricity_emission = Value, year = Time)
electricity_40 &lt;- electricity%&gt;%
  filter(State == &quot;State Total&quot;) %&gt;%
  select(-Pollutant, -Measure) %&gt;% 
  rename(electricity_emission = Value, year = Time)

electricity1</code></pre>
<pre><code>## # A tibble: 5 × 3
##   State        year electricity_emission
##   &lt;chr&gt;       &lt;dbl&gt;                &lt;dbl&gt;
## 1 State Total  2015                1901.
## 2 State Total  2016                1810.
## 3 State Total  2017                1733.
## 4 State Total  2018                1754.
## 5 State Total  2019                1608.</code></pre>
<pre class="r"><code>electricity_40</code></pre>
<pre><code>## # A tibble: 51 × 3
##    State        year electricity_emission
##    &lt;chr&gt;       &lt;dbl&gt;                &lt;dbl&gt;
##  1 State Total  1970                1061.
##  2 State Total  1971                1099.
##  3 State Total  1972                1192.
##  4 State Total  1973                1283.
##  5 State Total  1974                1249 
##  6 State Total  1975                1244.
##  7 State Total  1976                1352.
##  8 State Total  1977                1440.
##  9 State Total  1978                1447.
## 10 State Total  1979                1508.
## # … with 41 more rows</code></pre>
<pre class="r"><code>mod1 &lt;- lm(electricity_emission ~ year, data=electricity1)
coeff &lt;- coef(mod1)
print(coef)</code></pre>
<pre><code>## function (object, ...) 
## UseMethod(&quot;coef&quot;)
## &lt;bytecode: 0x7fabdd9d5620&gt;
## &lt;environment: namespace:stats&gt;</code></pre>
<pre class="r"><code>mod2 &lt;- lm(electricity_emission ~ year, data=electricity_40)
coeff2 &lt;- coef(mod2)
print(coeff2)</code></pre>
<pre><code>##  (Intercept)         year 
## -32984.49507     17.44551</code></pre>
<pre class="r"><code>ggplot(electricity_40, aes(year, electricity_emission)) +  geom_abline(intercept = coeff[1], slope = coeff[2], color = &quot;red&quot;, na.rm = FALSE) + geom_point() + geom_abline(intercept = coeff2[1], slope= coeff2[2], color = &quot;blue&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/electricity%20modeling-1.png" width="672" /></p>
<p>In the past 50 years, the overall pattern is a positive linear correlation between time and electricity emission in the US, we can see the slope is 17.44551 and the intercept is -32984.49507. So the equation to estimate electricity emission is electricity_emission = year * 17.44551 - 32984.49507. But during 2015-2019, there is a negative linear correlation between year and electricity emission, the slope is -64.3 and the intercept is 131454.2. Along with that line, we can see there is a clear tendency that the electricity emission in US is decreasing since 2005. So it is better to analyze the electricity emission in US by two periods of time.</p>
